@Library(value="ci@master", changelog=false) _

helm_hrms_generic([
    directoryPath: "charts/tenant-mgmt",
    imageName: "mynx-use1-hrms-stage-tenant-ecr",
    app: "tenant-mgmt",
    prefix: "mynx-use1",
    image_tag_helm_path: ".Deployment.containers.tenant-mgmt.image.tag"
])
